import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import DictionaryProvider from "@/context/DictionaryContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Capitech Dictionary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="lg:w-4/6 px-3 mx-auto">
          <DictionaryProvider>{children}</DictionaryProvider>
        </div>
      </body>
    </html>
  );
}
